repos:
- hooks:
  - id: autoflake
  repo: https://github.com/PyCQA/autoflake
  rev: v2.3.1
- hooks:
  - id: black
  repo: https://github.com/psf/black
  rev: 24.4.0
- hooks:
  - additional_dependencies:
    - tomli
    id: docformatter
  repo: https://github.com/PyCQA/docformatter
  rev: v1.7.5
- hooks:
  - id: isort
  repo: https://github.com/pycqa/isort
  rev: 5.13.2
